apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.serviceName }}
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.mariadb.port }}
      targetPort: {{ .Values.mariadb.targetPort }}
  type: ClusterIP